#!/bin/bash

mkdir -p ./reports
touch ./reports/build_report.json
touch ./reports/last_build.txt

while :
do
  docker run -t --rm -e SKIP_LINT=1 -e RUBY_ONLY=1 -e COMMIT_HASH=origin/tests-passed discourse/discourse_test:release | tee ./reports/last_build.txt
  docker run -t --rm -e SKIP_LINT=1 -e JS_ONLY=1 -e COMMIT_HASH=origin/tests-passed  discourse/discourse_test:release | tee -a ./reports/last_build.txt
  ruby ./investigate.rb '../../reports/last_build.txt' '../../reports/build_report.json'
done