#!/bin/bash

echo '===================================='
echo 'Downloading Docker'
echo '===================================='

wget -qO- https://get.docker.com/ | sh

echo '===================================='
echo 'Pulling discourse/discourse_test image.'
echo '===================================='

docker pull discourse/discourse_test:release
